[package]
name = "vectorized-exec-spi"
version = "0.1.0"
edition = "2021"
description = "Shared Rust utilities for OpenSearch vectorized execution"
license = "Apache-2.0"

[lib]
crate-type = ["rlib"]

[dependencies]
jni = { workspace = true }
linkme = "0.3"
libc = "0.2"
libmimalloc-sys = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
tokio = "1.52.0"

[dev-dependencies]
tokio = { workspace = true }
rayon = { workspace = true }
